apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "panope.agent.fullname" . }}
  labels:
    {{- include "panope.agent.labels" . | nindent 4 }}
  {{- with .Values.agent.clusterRole.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.agent.clusterRole.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - pods
  verbs:
  - get
  - list
  - watch
  - update
  - delete
- apiGroups:
  - ""
  resources:
  - pods/eviction
  verbs:
  - create
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
  - update
- apiGroups:
  - apps
  resources:
  - replicasets
  - daemonsets
  - statefulsets
  verbs:
  - get
  - list
  - watch
