apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "panope.agent.fullname" . }}-env
  labels:
    {{- include "panope.agent.labels" . | nindent 4 }}
  {{- with .Values.agent.configMap.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.agent.configMap.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  AGENT_SUBJECT: {{ required "Invalid value. Values.agent.configMap.agentSubject is required!" .Values.agent.configMap.agentSubject | quote }}
  CONTROLLER_SUBJECT: {{ required "Invalid value. Values.agent.configMap.controllerSubject is required!" .Values.agent.configMap.controllerSubject | quote }}
  NATS_URI: {{ required "Invalid value. Values.agent.configMap.natsUri is required!" .Values.agent.configMap.natsUri | quote }}
  CLUSTER_NODE_MAX_SURGE: {{ .Values.agent.configMap.clusterNodeMaxSurge |  quote }}
  MAX_PROCESSED_NODE_COUNT: {{ .Values.agent.configMap.maxProcessedNodeCount | quote }}
  HEALTH_CHECK_PORT: {{ .Values.agent.configMap.healthCheckPort | default "4444" | quote }}
  METRICS_PORT: {{ .Values.agent.configMap.metricsPort | default "2112" | quote }}
  ROLLING_UPDATE_TIMEOUT_SEC: {{ .Values.agent.configMap.rollingUpdateTimeoutSec | default "180" | quote }}
  DRAINING_TIMEOUT_SEC: {{ .Values.agent.configMap.drainingTimeoutSec | default "180" | quote }}
  FAILOVER_ENABLED: {{ .Values.agent.configMap.failoverEnabled | quote }}
