apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "panope.agent.fullname" . }}-env
  labels:
    {{- include "panope.agent.labels" . | nindent 4 }}
  {{- with .Values.agent.configMap.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.agent.configMap.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  SUBJECT: {{ required "Invalid value. Values.agent.configMap.subject is required!" .Values.agent.configMap.subject | quote }}
  NATS_URI: {{ required "Invalid value. Values.agent.configMap.natsUri is required!" .Values.agent.configMap.natsUri | quote }}
  HEALTH_CHECK_PORT: {{ .Values.agent.configMap.healthCheckPort | quote }}
  METRICS_PORT: {{ .Values.agent.configMap.metricsPort | quote }}
