apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "panope.agent.fullname" . }}
  labels:
    {{- include "panope.agent.labels" . | nindent 4 }}
  {{- with .Values.agent.deployment.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.agent.deployment.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.agent.replicaCount }}
  selector:
    matchLabels:
      {{- include "panope.agent.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "panope.agent.selectorLabels" . | nindent 8 }}
      {{- with .Values.agent.podLabels }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      annotations:
        checksum/secret: {{ include (print $.Template.BasePath "/agent/secret.yaml") . | sha256sum }}
      {{- with .Values.agent.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      terminationGracePeriodSeconds: 600 # for graceful shutdown
      volumes:
      - secret:
          secretName: {{ include "panope.agent.fullname" . }}
        name: {{ include "panope.agent.fullname" . }}-creds
      {{- if .Values.agent.secret.googleServiceAccountKeyfileJson }}
      - secret:
          secretName: {{ include "panope.agent.fullname" . }}-gcp-sa
        name: gcp-service-account-secret
      {{- end }}
      {{- with .Values.agent.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "panope.agent.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.agent.podSecurityContext | nindent 8 }}
      {{- if .Values.agent.priorityClassName }}
      priorityClassName: {{ .Values.agent.priorityClassName }}
      {{- end }}
      containers:
      - name: agent
        command:
        - bin/agent
        securityContext:
          {{- toYaml .Values.agent.securityContext | nindent 12 }}
        image: "{{ .Values.agent.image.repository }}:{{ .Values.agent.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.agent.image.pullPolicy }}
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        {{- if .Values.agent.secret.googleServiceAccountKeyfileJson }}
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /gcp-service-account/service-account-key.json
        {{- end }}
        ports:
          - name: http
            containerPort: {{ .Values.agent.configMap.healthCheckPort | default 4444 }}
            protocol: TCP
          - name: metrics
            containerPort: {{ .Values.agent.configMap.metricsPort | default 2112}}
            protocol: TCP
        livenessProbe:
          {{- toYaml .Values.agent.livenessProbe | trim | nindent 12 }}
        readinessProbe:
          {{- toYaml .Values.agent.readinessProbe | trim | nindent 12 }}
        resources:
          {{- toYaml .Values.agent.resources | nindent 12 }}
        envFrom:
        - configMapRef:
            name: {{ include "panope.agent.fullname" . }}-env
        volumeMounts:
        - mountPath: /agent/nats.creds
          name: {{ include "panope.agent.fullname" . }}-creds
          subPath: nats.creds
        {{- if .Values.agent.secret.googleServiceAccountKeyfileJson }}
        - mountPath: /gcp-service-account
          name: gcp-service-account-secret
        {{- end }}
      {{- with .Values.agent.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.agent.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.agent.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
