{{- if .Values.agent.pdb.enabled }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ include "panope.agent.fullname" . }}
  labels:
    {{- include "panope.agent.labels" . | nindent 4 }}
  {{- with .Values.agent.pdb.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.agent.pdb.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.agent.pdb.minAvailable }}
  minAvailable: {{ .Values.agent.pdb.minAvailable }}
  {{- else if .Values.agent.pdb.maxUnavailable }}
  maxUnavailable: {{ .Values.agent.pdb.maxUnavailable }}
  {{- else }}
  minAvailable: 0
  {{- end }}
  selector:
    matchLabels:
      {{- include "panope.agent.selectorLabels" . | nindent 6 }}
{{- end }}
