apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "panope.agent.fullname" . }}
  labels:
    {{- include "panope.agent.labels" . | nindent 4 }}
  {{- with .Values.agent.roleBinding.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.agent.roleBinding.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "panope.agent.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "panope.agent.fullname" . }}
  namespace: {{ .Release.Namespace }}
