{{- if .Values.agent.secret.googleServiceAccountKeyfileJson }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "panope.agent.fullname" . }}-gcp-sa
  labels:
    {{- include "panope.agent.labels" . | nindent 4 }}
  {{- with .Values.agent.secret.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.agent.secret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- if .Values.agent.secret.valuesAreBase64Encoded }}
  service-account-key.json: {{.Values.agent.secret.googleServiceAccountKeyfileJson | toString}}
  {{- else }}
  service-account-key.json: {{.Values.agent.secret.googleServiceAccountKeyfileJson | toString | b64enc}}
  {{- end }}
{{- end }}
