apiVersion: v1
kind: Secret
metadata:
  name: {{ include "panope.agent.fullname" . }}
  labels:
    {{- include "panope.agent.labels" . | nindent 4 }}
  {{- with .Values.agent.secret.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.agent.secret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  nats.creds: {{ required "Invalid value. Values.agent.secret.nats.credentials is required!" .Values.agent.secret.nats.credentials | b64enc }}
