{{- if .Values.agent.serviceMonitor.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "panope.agent.fullname" . }}
  labels:
    {{- include "panope.agent.labels" . | nindent 4 }}
  {{- with .Values.agent.service.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.agent.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ports:
  - name: metrics
    port: {{ .Values.agent.configMap.metricsPort | int }}
    protocol: TCP
    targetPort: {{ .Values.agent.configMap.metricsPort | int }}
  selector:
    {{- include "panope.agent.selectorLabels" . | nindent 4 }}
  sessionAffinity: None
  type: ClusterIP
{{- end -}}
