apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "panope.agent.fullname" . }}
  labels:
    {{- include "panope.agent.labels" . | nindent 4 }}
  {{- with .Values.agent.serviceAccount.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.agent.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
    
