apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "panope.observer.fullname" . }}
  labels:
    {{- include "panope.observer.labels" . | nindent 4 }}
  {{- with .Values.observer.clusterRoleBinding.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.observer.clusterRoleBinding.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "panope.observer.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "panope.observer.fullname" . }}
  namespace: {{ .Release.Namespace }}
