apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "panope.observer.fullname" . }}-env
  labels:
    {{- include "panope.observer.labels" . | nindent 4 }}
  {{- with .Values.observer.configMap.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.observer.configMap.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  HEALTH_CHECK_PORT: {{ .Values.observer.configMap.healthCheckPort | quote }}
  METRICS_PORT: {{ .Values.observer.configMap.metricsPort | quote }}
