apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "panope.observer.fullname" . }}-env
  labels:
    {{- include "panope.observer.labels" . | nindent 4 }}
  {{- with .Values.observer.configMap.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.observer.configMap.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  HEALTH_CHECK_PORT: {{ .Values.observer.configMap.healthCheckPort | quote }}
  METRICS_PORT: {{ .Values.observer.configMap.metricsPort | quote }}
  OBSERVER_SUBJECT: {{ required "Invalid value. Values.observer.configMap.observerSubject is required!" .Values.observer.configMap.observerSubject | quote }}
  CONTROLLER_SUBJECT: {{ required "Invalid value. Values.observer.configMap.controllerSubject is required!" .Values.observer.configMap.controllerSubject | quote }}
  NATS_URI: {{ required "Invalid value. Values.observer.configMap.natsUri is required!" .Values.observer.configMap.natsUri | quote }}

