apiVersion: v1
kind: Secret
metadata:
  name: {{ include "panope.observer.fullname" . }}
  labels:
    {{- include "panope.observer.labels" . | nindent 4 }}
  {{- with .Values.observer.secret.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.observer.secret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  nats.creds: {{ required "Invalid value. Values.observer.secret.nats.credentials is required!" .Values.observer.secret.nats.credentials | b64enc }}
