# https://github.com/helm/chart-testing-action#example-workflow
name: Lint and Test Charts
on: pull_request

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3.3
        with:
          version: v3.7.1

      - uses: actions/setup-python@v4.1.0
        with:
          python-version: 3.7

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.3.0

      - name: Run chart-testing (lint)
        run: ct lint --config .github/ct-lint.yaml
